MyTwitter-master/lib/twitter_web/router.ex
defmodule Twitter_backend.Router do
  use Twitter_backend, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: Twitter_backend.Token
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Twitter_backend do
    pipe_through :browser 
    
    get "/", SessionController, :new
    resources "/users", UserController, [:new, :create]
    resources "/sessions", SessionController, only: [:create, :delete]
  end

  scope "/", Twitter_backend do
    pipe_through [:browser, :browser_auth]
    
    get "/home", PageController, :home

    get "/sendtweet", TweetController, :sendtweetindex
    resources "/tweet", TweetController, only: [:create]

    get "/subscribeto", UserController, :sub_indie
    post "/users/subscribe", UserController, :subscribe

    get "/querytweet", TweetController, :querytweetindex
    post "/querytweet/fromsubscriber", TweetController, :query_subs
    post "/querytweet/frommentioned", TweetController, :query_mention
    post "/querytweet/fromhashtag", TweetController, :query_hashtag
    
    resources "/retweet", RetweetController
  end
  # Other scopes may use custom stacks.
  # scope "/api", Twitter_backend do
  #   pipe_through :api
  # end
end

MyTwitter-master/lib/twitter_web/templates/page/home.html.eex
<div>
  <h1>User Home Page</h1>
  <ul>
    <li>
      User_name:
      <%= @user.username %>
    </li>
    <li>
      Subscribe:
      <%= @user.subscribe %>
    </li>
    <li>
      Follower:
      <%= @user.follower %>
    </li>

</ul>
</div>


<%= link "Tweet", to: tweet_path(@conn, :sendtweetindex)%>
<br>
<%= link "Search for tweets", to: tweet_path(@conn, :querytweetindex) %>
<br>
<%= link "Follow another twitter user", to: user_path(@conn, :sub_indie) %>
<br>
<%= link "Sign Out", to: session_path(@conn, :delete, :access), method: :delete%>
<br><br><br>

<%= for tweet <- @tweetslive do %>
         <strong>TWEET "</strong>
         <%=tweet.content %>"
         <strong>By</strong>
         <%= tweet.author %>
       <%= link "Retweet-this-tweet", to: retweet_path(@conn, :show, tweet) %>     
       <br><br>
<% end %>